name: build-windows-release

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: choco install wget unzip ninja -y --no-progress

      - name: Install Skia
        run: |
          wget https://github.com/aseprite/skia/releases/download/m102-861e4743af/Skia-Windows-Release-x64.zip
          unzip Skia-Windows-Release-x64.zip -d skia

      - name: Setup MSVC environment
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Generate build files
        shell: bash
        run: |
          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DLAF_BACKEND=skia \
            -DSKIA_DIR=skia \
            -DSKIA_LIBRARY_DIR=skia/out/Release-x64 \
            -DSKIA_LIBRARY=skia/out/Release-x64/skia.lib

      - name: Build aseprite
        run: cmake --build build --target aseprite

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: aseprite-windows
          path: build/bin/aseprite.exe
