name: build-windows-release

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Install Dependencies
        run: choco install wget unzip ninja -y --no-progress

      - name: Install Skia
        run: |
          wget https://github.com/aseprite/skia/releases/download/m102-861e4743af/Skia-Windows-Release-x64.zip
          unzip Skia-Windows-Release-x64.zip -d skia

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Generate CMake files
        shell: bash
        run: |
          export enable_ccache=off
          export laf_backend=skia
          export enable_scripting=on
          export skia_arch=x64

          # Workaround for libarchive expecting version file
          mkdir -p third_party/libarchive/build
          echo "3.6.1" > third_party/libarchive/build/version

          cmake -S . -B build -G Ninja \
            -DCMAKE_BUILD_TYPE=RelWithDebInfo \
            -DENABLE_TESTS=ON \
            -DENABLE_SCRIPTING=$enable_scripting \
            -DENABLE_CCACHE=$enable_ccache \
            -DLAF_BACKEND=$laf_backend \
            -DSKIA_DIR=skia \
            -DSKIA_LIBRARY_DIR=skia/out/Release-$skia_arch

      - name: Compile Aseprite
        run: cmake --build build

      - name: Run C++ Tests
        run: |
          cd build
          ctest --output-on-failure
