name: Build Aseprite for Windows

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [ main ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout Aseprite
      uses: actions/checkout@v3
      with:
        repository: aseprite/aseprite
        submodules: recursive

    - name: Set up dependencies
      uses: lukka/get-cmake@latest

    - name: Install dependencies
      run: |
        choco install ninja git -y
        git config --global core.autocrlf input

    - name: Clone Skia
      run: |
        git clone https://github.com/aseprite/skia.git skia
        cd skia
        python3 tools/git-sync-deps
        bin/gn gen out/Release --args="is_official_build=true skia_use_system_libpng=false skia_use_system_zlib=false target_os=\"win\""
        ninja -C out/Release

    - name: Configure Aseprite
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo `
              -DLAF_BACKEND=skia `
              -DSKIA_DIR=${{ github.workspace }}\skia `
              -DSKIA_OUT_DIR=${{ github.workspace }}\skia\out\Release `
              -G Ninja ..\

    - name: Build Aseprite
      run: |
        cd build
        ninja

    - name: Upload executable
      uses: actions/upload-artifact@v4
      with:
        name: aseprite-windows
        path: build\bin\aseprite.exe
