name: build-windows-release

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: choco install wget unzip ninja -y --no-progress

      - name: Install Skia
        run: |
          wget https://github.com/aseprite/skia/releases/download/m102-861e4743af/Skia-Windows-Release-x64.zip
          unzip Skia-Windows-Release-x64.zip -d skia

      - name: Locate Visual Studio installation
        shell: cmd
        run: |
          vswhere.exe -latest -property installationPath


      - name: Setup MSVC environment
        shell: cmd
        run: |
          for /f "delims=" %%i in ('vswhere.exe -latest -property installationPath') do set VS_PATH=%%i
          call "%VS_PATH%\Common7\Tools\VsDevCmd.bat" -arch=x64

      - name: Build aseprite
        shell: cmd
        run: |
          for /f "delims=" %%i in ('vswhere.exe -latest -property installationPath') do set VS_PATH=%%i
          call "%VS_PATH%\Common7\Tools\VsDevCmd.bat" -arch=x64
          #cd aseprite
          mkdir build
          cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DLAF_BACKEND=skia -DSKIA_DIR=..\..\skia -DSKIA_LIBRARY_DIR=..\..\skia\out\Release-x64 -DSKIA_LIBRARY=..\..\skia\out\Release-x64\skia.lib ..
          ninja aseprite


      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: aseprite-windows
          path: aseprite\build\bin\aseprite.exe
