name: build-windows-release

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: choco install wget unzip ninja -y --no-progress

      - name: Install Skia
        run: |
          wget https://github.com/aseprite/skia/releases/download/m102-861e4743af/Skia-Windows-Release-x64.zip
          unzip Skia-Windows-Release-x64.zip -d skia

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1



      - name: Configure and build (MSVC)
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" -arch=x64
          cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DLAF_BACKEND=skia -DSKIA_DIR=skia -DSKIA_LIBRARY_DIR=skia/out/Release-x64 -DSKIA_LIBRARY=skia/out/Release-x64/skia.lib
          cmake --build build --target aseprite



      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: aseprite-windows
          path: build/bin/aseprite.exe
